version: '3'

services:
  node-app:
    image: node:alpine
    container_name: dev-express
    working_dir: /app
    ports:
      - "${PORT_CLIENT}:${PORT_CLIENT}"
    command: sh -c 'cd /app && yarn && yarn dev'
    volumes:
      - ../:/app
      - ./node_modules:/app/node_modules
    networks:
      - node-network

  mongodb:
    image: mongo
    container_name: dev-mongo
    ports:
      - "${PORT_MONGO}:${PORT_MONGO}"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - node-network

volumes:
  mongo-data:
  mongo-config:

networks:
  node-network:
    driver: bridge

