version: '3'

services:
  node-app:
    image: node:alpine
    container_name: dev-express
    working_dir: /app
    ports:
      - '8888:8888'
    command: sh -c 'cd /app && yarn && yarn dev'
    volumes:
      - ../:/app
      - ./node_modules:/app/node_modules

