FROM node:alpine

RUN mkdir -p /node-app && chown -R node:node /node-app

WORKDIR /node-app

COPY package.json yarn.lock ./

USER node

RUN yarn install --pure-lockfile

COPY --chown=node:node . .

EXPOSE 3333

